Fix error during package_qa with aktualizr-ptest
Oddly, this started happening:

    ERROR: aktualizr-1.0+gitAUTOINC+03778511cc-7 do_package_qa: QA Issue:
    /usr/lib/aktualizr/ptest/src/tests/sota_tools/headers_response_server.py
    contained in package aktualizr-ptest requires /usr/bin/python3, but no
    providers found in RDEPENDS_aktualizr-ptest? [file-rdeps]

However, the python3 binary is already provided by python3-modules but
for some reason the qa check tool trips on it. We need to add an
explicit `python3-core` in the list.

Signed-off-by: Laurent Bonnans <laurent.bonnans@here.com>